### ISSUE TITLE
Lib version mismatch when running dbt 1.10 in databricks job task

### ISSUE THREAD

**Issue by septponf** [databricks/dbt-databricks#1150]
I just wanted to share that after upgrading dbt to 1.10.8 from 1.9 I got an issue when executing the project using the built-in databricks dbt job task.

```
Encountered an error:
module 'urllib3' has no attribute 'BaseHTTPResponse'
```

The job is run on a single node Standard_DS2_V2 Release 15.4.21
I assume there is some mismatch with the pre-installed libs on the cluster.
I got it to work by, in the task settings, specifying the versions of databricks-sql-connector and urllib in addition to dbt.

```
dbt-core==1.10.8
dbt-databricks==1.10.9
databricks-sql-connector>=4.0.5
urllib3==2.2.3
```

[urllib_error.txt](https://github.com/user-attachments/files/21855436/urllib_error.txt)
