### ISSUE TITLE
No macro named 'alter_view' error when running dbt compile with dbt-databricks 1.10.0

### ISSUE THREAD

**Issue by grdl** [databricks/dbt-databricks#1002]
### Describe the bug
When running `dbt compile` with dbt-databricks 1.10.0, we're getting the following error:
```
Compilation Error
  In dispatch: No macro named 'alter_view' found within namespace: 'databricks'
      Searched for: 'databricks.databricks__alter_view', 'databricks.spark__alter_view', 'databricks.default__alter_view', 'databricks.databricks__alter_view', 'databricks.spark__alter_view', 'databricks.default__alter_view'
```

### Steps To Reproduce

- Create an empty folder
- Add `dbt_project.yml` file with the following content:
```
name: "databricks"
version: "1.0.0"
config-version: 2
profile: "databricks"
```
- Add `requirements.txt` file with the following content:
```
dbt-databricks==1.10.0
```
- Create and activate Python virtual environment:
```
python -m venv .venv
source .venv/bin/activate
``` 
- Install Python deps:
```
pip install -r requirements.txt
```
- Run dbt deps and dbt compile:
```
dbt deps
dbt compile
```

### Expected behavior

I expect a successful `dbt compile` command. Here's an example using dbt-databricks 1.9.7:
```
> dbt compile
16:01:39  Running with dbt=1.9.4
16:01:39  Registered adapter: databricks=1.9.7
16:01:40  Unable to do partial parsing because saved manifest not found. Starting full parse.
16:01:40  Found 607 macros
16:01:40  Nothing to do. Try checking your model configs and model specification args
```

### Screenshots and log output

Here's the example of unsuccessful `dbt compile` command using dbt-databricks 1.10.0:
```
> dbt compile
16:03:10  Running with dbt=1.9.4
16:03:10  Registered adapter: databricks=1.10.0
16:03:11  Encountered an error:
Compilation Error
  In dispatch: No macro named 'alter_view' found within namespace: 'databricks'
      Searched for: 'databricks.databricks__alter_view', 'databricks.spark__alter_view', 'databricks.default__alter_view', 'databricks.databricks__alter_view', 'databricks.spark__alter_view', 'databricks.default__alter_view'
```

### System information
**The output of `dbt --version`:**
```
❯ dbt --version
Core:
  - installed: 1.9.4
  - latest:    1.9.4 - Up to date!

Plugins:
  - databricks: 1.10.0 - Up to date!
  - spark:      1.9.2  - Up to date!
```

**The operating system you're using:**
MacOS 14.7.5

**The output of `python --version`:**
```
Python 3.10.13
```

**Comment by benc-db** [comment]
Are you certain this happens on a clean venv?  I am unable to repro this.  When we've seen this sort of issue in the past, it came from trying to upgrade in place.

**Comment by grdl** [comment]
Hi @benc-db . Yes, I'm positive this happens on a clean venv. Also, a few folks from my team followed the steps to reproduce and got the same error too.

**Comment by benc-db** [comment]
Interesting.  I can repro if I literally follow the steps, i.e. I don't have a real dbt project.  On my personal dbt project, even with a clean venv, I cannot repro.  Will need to ask dbt Labs folks why this might be.

**Comment by benc-db** [comment]
As soon as I bring this environment over to my dbt project, dbt compile doesn't show this behavior.  Do you have an actual dbt project showing this behavior?

**Comment by grdl** [comment]
Thanks @benc-db . It does seem to be caused by the name clash. When I changed the project name to "databricks_companyname" the compile command finishes correctly. Thanks for your help!
